"""add default diagnostic model

Revision ID: 30d2cc3e4364
Revises: 70959cee10e1
Create Date: 2026-05-14 12:46:33.273602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d2cc3e4364'
down_revision: Union[str, Sequence[str], None] = '70959cee10e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defaultdiagnostic',
    sa.Column('diagnostic_run_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnosticrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defaultdiagnostic_diagnostic_run_id'), 'defaultdiagnostic', ['diagnostic_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defaultdiagnostic_diagnostic_run_id'), table_name='defaultdiagnostic')
    op.drop_table('defaultdiagnostic')
    # ### end Alembic commands ###
