"""add diagnostic run model


Revision ID: 70959cee10e1
Revises: 70ab808d938f
Create Date: 2026-05-14 09:12:42.559889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '70959cee10e1'
down_revision: Union[str, Sequence[str], None] = '70ab808d938f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'diagnosticrun',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('diagnostic_code', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('voice_file_id', sa.Integer(), nullable=True),
        sa.Column('result_file_id', sa.Integer(), nullable=True),
        sa.Column('transcribation_file_id', sa.Integer(), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tag', sa.String(length=255), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['result_file_id'], ['file.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['transcribation_file_id'], ['file.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['voice_file_id'], ['file.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_diagnosticrun_diagnostic_code'), 'diagnosticrun', ['diagnostic_code'], unique=False)
    op.create_index(op.f('ix_diagnosticrun_status'), 'diagnosticrun', ['status'], unique=False)
    op.create_index(op.f('ix_diagnosticrun_user_id'), 'diagnosticrun', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosticrun_user_id'), table_name='diagnosticrun')
    op.drop_index(op.f('ix_diagnosticrun_status'), table_name='diagnosticrun')
    op.drop_index(op.f('ix_diagnosticrun_diagnostic_code'), table_name='diagnosticrun')
    op.drop_table('diagnosticrun')
    # ### end Alembic commands ###
