"""add telegram user profile cascade delete

Revision ID: 71d6c9bedd7b
Revises: 53ad66fd2c15
Create Date: 2026-05-03 12:51:14.913900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d6c9bedd7b'
down_revision: Union[str, Sequence[str], None] = '53ad66fd2c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('userprofile_telegram_user_id_fkey'), 'userprofile', type_='foreignkey')
    op.create_foreign_key(
        'userprofile_telegram_user_id_fkey',
        'userprofile',
        'telegramuser',
        ['telegram_user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userprofile_telegram_user_id_fkey', 'userprofile', type_='foreignkey')
    op.create_foreign_key(op.f('userprofile_telegram_user_id_fkey'), 'userprofile', 'telegramuser', ['telegram_user_id'], ['id'])
    # ### end Alembic commands ###
