"""update telegram models

Revision ID: a3da97885973
Revises: c4d5e6f7a8b9
Create Date: 2026-05-17 12:19:54.860225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3da97885973'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramuser', 'first_name')
    op.drop_column('telegramuser', 'last_name')
    op.add_column('userprofile', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('userprofile', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'city')
    op.drop_column('userprofile', 'date_of_birth')
    op.add_column('telegramuser', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('telegramuser', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
