"""init

Revision ID: be77a67bbd25
Revises: 
Create Date: 2026-05-19 11:26:12.139885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be77a67bbd25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('link', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegramuser',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocket_bot', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegramuser_telegram_id'), 'telegramuser', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_telegramuser_username'), 'telegramuser', ['username'], unique=False)
    op.create_table('analysisregistration',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysisregistration_user_id'), 'analysisregistration', ['user_id'], unique=False)
    op.create_table('corerequest',
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('difficulties', sa.Text(), nullable=True),
    sa.Column('readiness', sa.String(length=255), nullable=True),
    sa.Column('weekly_time', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.String(length=255), nullable=True),
    sa.Column('payment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corerequest_user_id'), 'corerequest', ['user_id'], unique=False)
    op.create_table('diagnosticrun',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_code', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('voice_file_id', sa.Integer(), nullable=True),
    sa.Column('result_file_id', sa.Integer(), nullable=True),
    sa.Column('transcribation_file_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['result_file_id'], ['file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcribation_file_id'], ['file.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_file_id'], ['file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosticrun_diagnostic_code'), 'diagnosticrun', ['diagnostic_code'], unique=False)
    op.create_index(op.f('ix_diagnosticrun_status'), 'diagnosticrun', ['status'], unique=False)
    op.create_index(op.f('ix_diagnosticrun_user_id'), 'diagnosticrun', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('product_code', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_code'), 'product', ['product_code'], unique=False)
    op.create_index(op.f('ix_product_user_id'), 'product', ['user_id'], unique=False)
    op.create_table('userprofile',
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegramuser.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defaultdiagnostic',
    sa.Column('diagnostic_run_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnosticrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defaultdiagnostic_diagnostic_run_id'), 'defaultdiagnostic', ['diagnostic_run_id'], unique=True)
    op.create_table('invisiblediagnostic',
    sa.Column('diagnostic_run_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnosticrun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invisiblediagnostic_diagnostic_run_id'), 'invisiblediagnostic', ['diagnostic_run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invisiblediagnostic_diagnostic_run_id'), table_name='invisiblediagnostic')
    op.drop_table('invisiblediagnostic')
    op.drop_index(op.f('ix_defaultdiagnostic_diagnostic_run_id'), table_name='defaultdiagnostic')
    op.drop_table('defaultdiagnostic')
    op.drop_table('userprofile')
    op.drop_index(op.f('ix_product_user_id'), table_name='product')
    op.drop_index(op.f('ix_product_product_code'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_diagnosticrun_user_id'), table_name='diagnosticrun')
    op.drop_index(op.f('ix_diagnosticrun_status'), table_name='diagnosticrun')
    op.drop_index(op.f('ix_diagnosticrun_diagnostic_code'), table_name='diagnosticrun')
    op.drop_table('diagnosticrun')
    op.drop_index(op.f('ix_corerequest_user_id'), table_name='corerequest')
    op.drop_table('corerequest')
    op.drop_index(op.f('ix_analysisregistration_user_id'), table_name='analysisregistration')
    op.drop_table('analysisregistration')
    op.drop_index(op.f('ix_telegramuser_username'), table_name='telegramuser')
    op.drop_index(op.f('ix_telegramuser_telegram_id'), table_name='telegramuser')
    op.drop_table('telegramuser')
    op.drop_table('file')
    # ### end Alembic commands ###
