global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      # Оставляем только контейнерные метрики (убираем /machine, /system.slice и т.д.)
      - source_labels: [id]
        regex: '/docker/.+'
        action: keep
