export const initialUsers = [
  {
    id: 1,
    telegram_id: "582832648",
    username: "ivan_ivanov",
    full_name: "Иван Иванов",
    phone: "+7 (999) 111-22-33",
    city: "Москва",
    email: "ivanov@example.com",
    timezone: "UTC+3 (MSK)",
    birth_date: "12.05.1988",
    registration_date: "10.01.2024",
    last_active: "Сегодня, 10:05",
    in_core: true,
    current_step: "Шаг 4: Мотивация",
    step_status: "В процессе",
    notes: "Лояльный клиент, проходил 3 курса. Интересуется темой масштабирования команды.",
    source: "Добавлен вручную администратором.",
    channel_subscribed: true,
    channel_check_date: "Сегодня",
    methodology_received: true,
    methodology_date: "Выдана 13.03.2024 в 14:20",
    core_form: {
      filled: true,
      updated_at: "Обновлено 2 часа назад",
      activity: "Заявка в компании, разработка финтех-решений для малого бизнеса.",
      request: "Хочу вырасти в 5 раз за год. Сейчас уперся в потолок, операционка съедает всё время.",
      priorities: ["Масштабирование", "Делегирование", "Мышление"],
      readiness: "Высокая",
      weekly_time: "10-15 ч.",
      difficulties: "Боюсь потерять контроль над качеством продукта при быстром росте команды.",
      payment_status: "ОПЛАЧЕНО",
      feedback: "Согласен",
      feedback_log: "лог: 192.168.1.5"
    },
    diagnostics: [
      { code: "D-01", name: "Личностный масштаб", status: "Готово", date: "12.03.2024 в 11:30", voice: true, report: true, transcript: true },
      { code: "D-02", name: "Эмоциональный интеллект", status: "Прервано", date: "14.03.2024 в 18:45", voice: false, report: false, transcript: false }
    ]
  },
  {
    id: 2,
    telegram_id: "370621610",
    username: "mariya_psy",
    full_name: "Мария Соколова",
    phone: "+7 (999) 222-33-44",
    city: "Санкт-Петербург",
    email: "mariya.s@example.com",
    timezone: "UTC+3 (MSK)",
    birth_date: "24.08.1991",
    registration_date: "15.02.2024",
    last_active: "Вчера, 23:45",
    in_core: false,
    current_step: "Шаг 1: Приветствие",
    step_status: "Не начата",
    notes: "Психолог, хочет внедрить методику масштабирования в свои психологические сессии и коучинг программы.",
    source: "Органический трафик из ТГ канала.",
    channel_subscribed: true,
    channel_check_date: "Вчера",
    methodology_received: false,
    methodology_date: "Ожидает",
    core_form: {
      filled: false,
    },
    diagnostics: [
      { code: "D-02", name: "Эмоциональный интеллект", status: "Готово", date: "24.04.2024 в 15:20", voice: true, report: true, transcript: true }
    ]
  },
  {
    id: 3,
    telegram_id: "908123456",
    username: "alex_grom",
    full_name: "Александр Громов",
    phone: "+7 (999) 333-44-55",
    city: "Екатеринбург",
    email: "gromov.estate@example.com",
    timezone: "UTC+5",
    birth_date: "05.11.1983",
    registration_date: "01.03.2024",
    last_active: "Сегодня, 08:22",
    in_core: true,
    current_step: "Шаг 2: Диагностика",
    step_status: "Получена",
    notes: "Строит агентство недвижимости. Быстро отвечает, заинтересован в масштабировании своего отдела продаж и делегировании звонков.",
    source: "Лид-магнит (Методичка PML)",
    channel_subscribed: true,
    channel_check_date: "Сегодня",
    methodology_received: true,
    methodology_date: "Линк отправлен в бот",
    core_form: {
      filled: true,
      updated_at: "Обновлено 1 день назад",
      activity: "Основатель агентства недвижимости в Екатеринбурге (штат 25 человек).",
      request: "Хочу отойти от операционки, так как контролирую каждую сделку самостоятельно.",
      priorities: ["Делегирование", "Систематизация"],
      readiness: "Высокая",
      weekly_time: "8-10 ч.",
      difficulties: "Сотрудники не умеют продавать без моего личного вовлечения.",
      payment_status: "ОПЛАЧЕНО",
      feedback: "Согласен",
      feedback_log: "лог: 192.168.2.11"
    },
    diagnostics: [
      { code: "D-01", name: "Личностный масштаб", status: "Готово", date: "02.03.2024 в 16:40", voice: true, report: true, transcript: true },
      { code: "D-03", name: "Архетипы власти", status: "Готово", date: "05.03.2024 в 10:15", voice: true, report: true, transcript: true }
    ]
  },
  {
    id: 4,
    telegram_id: "102938475",
    username: "markova_elena",
    full_name: "Елена Маркова",
    phone: "+7 (999) 444-55-66",
    city: "Казань",
    email: "elena.m@example.com",
    timezone: "UTC+3 (MSK)",
    birth_date: "14.02.1990",
    registration_date: "12.03.2024",
    last_active: "1д назад",
    in_core: false,
    current_step: "Шаг 3: Соглашение",
    step_status: "Не начата",
    notes: "Представитель консалтинговой компании, вошла через партнерский вебинар.",
    source: "Партнерский вебинар",
    channel_subscribed: false,
    channel_check_date: "1д назад",
    methodology_received: false,
    methodology_date: "Ожидает",
    core_form: { filled: false },
    diagnostics: []
  },
  {
    id: 5,
    telegram_id: "564738291",
    username: "igor_p",
    full_name: "Игорь Петров",
    phone: "+7 (999) 555-66-77",
    city: "Новосибирск",
    email: "petrov.consult@example.com",
    timezone: "UTC+7",
    birth_date: "30.09.1995",
    registration_date: "20.03.2024",
    last_active: "4д назад",
    in_core: false,
    current_step: "Шаг 1",
    step_status: "Не начата",
    notes: "Зарегистрировался в боте из любопытства. Информацией о бизнесе пока не делился.",
    source: "Органический поиск",
    channel_subscribed: false,
    channel_check_date: "4д назад",
    methodology_received: false,
    methodology_date: "Ожидает",
    core_form: { filled: false },
    diagnostics: []
  },
  {
    id: 6,
    telegram_id: "778899001",
    username: "alex_wolf",
    full_name: "Александр Вольф",
    phone: "+7 (999) 777-88-99",
    city: "Сочи",
    email: "wolf.ceo@example.com",
    timezone: "UTC+3 (MSK)",
    birth_date: "19.07.1979",
    registration_date: "05.02.2024",
    last_active: "2м назад",
    in_core: true,
    current_step: "Шаг 5: Итоги",
    step_status: "Получена",
    notes: "Серийный предприниматель, имеет несколько бизнесов.",
    source: "Прямой переход",
    channel_subscribed: true,
    channel_check_date: "2м назад",
    methodology_received: true,
    methodology_date: "Выдана 10.02.2024",
    core_form: {
      filled: true,
      updated_at: "Обновлено 2 месяца назад",
      activity: "Производство эко-упаковки.",
      request: "Интересует построение совета директоров и выход из ежедневной рутины.",
      priorities: ["Делегирование", "Совет директоров"],
      readiness: "Высокая",
      weekly_time: "10-15 ч.",
      difficulties: "Некому передать ключевой бизнес-процесс.",
      payment_status: "ОПЛАЧЕНО",
      feedback: "Согласен",
      feedback_log: "лог: 192.168.3.4"
    },
    diagnostics: [
      { code: "D-03", name: "Архетипы власти", status: "Готово", date: "06.02.2024 в 10:00", voice: true, report: true, transcript: true }
    ]
  },
  {
    id: 7,
    telegram_id: "889900112",
    username: "dmitry_stroy",
    full_name: "Дмитрий Кузнецов",
    phone: "+7 (999) 888-99-00",
    city: "Краснодар",
    email: "kuznecov@example.com",
    timezone: "UTC+3 (MSK)",
    birth_date: "22.10.1985",
    registration_date: "10.03.2024",
    last_active: "15м назад",
    in_core: true,
    current_step: "Шаг 3: Франшиза",
    step_status: "Получена",
    notes: "Строительная компания. Высокий средний чек, хочет масштабироваться по франшизе.",
    source: "Спец-проект Франшизы",
    channel_subscribed: true,
    channel_check_date: "15м назад",
    methodology_received: true,
    methodology_date: "Выдана 11.03.2024",
    core_form: {
      filled: true,
      updated_at: "Обновлено 15 минут назад",
      activity: "Малоэтажное строительство в ЮФО.",
      request: "Цель: упаковать франшизу и продать 10 точек за первый год.",
      priorities: ["Франшиза", "Систематизация"],
      readiness: "Высокая",
      weekly_time: "12-15 ч.",
      difficulties: "Сложно описать стандарты качества строительных работ в регионах.",
      payment_status: "НЕ ОПЛАЧЕНО",
      feedback: "Согласен",
      feedback_log: "лог: 192.168.4.15"
    },
    diagnostics: [
      { code: "D-01", name: "Личностный масштаб", status: "Готово", date: "11.03.2024 в 14:00", voice: true, report: true, transcript: true }
    ]
  }
];

export const initialBroadcasts = [
  {
    id: 101,
    status: "Отправлено",
    time_label: "Сегодня, 10:20",
    text: "Приветствую! Мы обновили нашу главную методичку по психологии масштаба.\nСкачать ее вы можете, нажав на кнопку ниже.\nЖелаем продуктивного дня!",
    reach: 124,
    targeting: {
      segment: "Все",
      diagnostics: "Все диагностики",
      only_with_methodology: false
    }
  },
  {
    id: 102,
    status: "Отправлено",
    time_label: "Вчера, 18:00",
    text: "Внимание участников Ядра!\nСегодня в 19:00 по МСК состоится закрытая онлайн-диагностика Личностного Масштаба.\nСсылка на эфир придет за 10 минут до старта.",
    reach: 48,
    targeting: {
      segment: "В ядре",
      diagnostics: "Личностный масштаб",
      only_with_methodology: true
    }
  },
  {
    id: 103,
    status: "Запланировано",
    time_label: "Завтра, 12:00",
    text: "Авто-напоминание!\nВы зарегистрировались на разбор, но не завершили диагностику Архетипов Власти.\n\nПожалуйста, пройдите опрос до конца, чтобы психолог получил репрезентативную картину.",
    reach: 15,
    targeting: {
      segment: "Все",
      diagnostics: "Архетипы власти",
      only_with_methodology: false
    }
  }
];
